# The labels in this file are automatically synced with the
# repository using the micnncim/action-label-syncer action.
- name: bug
  color: d73a4a
  description: 'bug'
- name: enhancement
  color: a2eeef
  description: 'enhancement'

- name: dependencies
  color: 1abc9c
  description: 'dependencies'

- name: PR-block
  color: cfd3d7
  description: 'Pull Request: Do not merge'
- name: PR-merge
  color: a3f41c
  description: 'Pull Request: Merge when ready'
