name: Init Template Create

on:
  create:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3.1.0

      - run: |
          REPO_NAME=${{ github.event.repository.name }}
          cp .github/template/README.md README.md
          rm -rf .github/template
          rm .github/workflows/init-template-create.yml
          rm LICENSE
          sed -i "s/\[date\]/$(date '+%Y-%m-%d %T')/g" README.md
          sed -i "s/\[repo\]/$REPO_NAME/g" README.md

      - uses: peter-evans/create-pull-request@v4
        with:
          commit-message: init template create
          branch: create-pull-request/init-template-create
          delete-branch: true
          title: '[create-pull-request] init template create'
